### ISSUE TITLE
./configure fails

### ISSUE THREAD

**Issue by RyDroid** [dsw/oink-stack#12]
```
$ ./configure
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at ./configure.pl line 109.
```

It seems to be a problem with recent Perl versions. https://github.com/kentcdodds/cloc/issues/1

**Comment by dsw** [comment]
Thanks for the bug report.  Can I trouble you to make that change and check
that it works?

If you would write me separately to my personal email, I would be
interested to hear what you are using Elsa/Oink for.

**Comment by RyDroid** [comment]
I tried but failed. I never wrote some Perl code.
I just would have liked to make one of my personal C project analyzed by an other tool to find potential new problems.

**Comment by dsw** [comment]
A fix is merged now.
