### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [dsw/oink-stack#26]
I've just did a conversion of https://github.com/dsw/oink-stack/blob/master/elsa/cc.gr to an `EBNF` that can be used to generate a nice navigable railroad diagram and it can be viewd here https://mingodad.github.io/cpp-grammars/elsa-cc.gr.ebnf.xhtml , the `EBNF` is here https://github.com/mingodad/cpp-grammars/blob/main/elsa-cc.gr.ebnf .

Thee you'll find `EBNF` and railroad diagrams for other `C++` grammars.

**Comment by dsw** [comment]
Ok.  It's fun to look at.  Do you need anything from me?

**Comment by mingodad** [comment]
Thank you for reply !

It's only to acknowledge it's existence, in my opinion it's a helper to visualize/debug/develop it further.

**Comment by mingodad** [comment]
By the way there is a revised version of elkhound/smbase/ast/elsa here https://github.com/smcpeak/

**Comment by dsw** [comment]
Well Scott seems to be maintaining his own copy.  He is the designer and
implementer of Elkhound and is the designer and original implementer of
Elsa, so this is unsurprising.  Thanks for letting me know about it though.

Daniel
